apiVersion: v1
kind: Secret
metadata:
  name: {{ include "idenplane.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "idenplane.labels" . | nindent 4 }}
  annotations:
    # Helm will not diff secret values in plain text.
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  ADMIN_API_KEY: {{ .Values.secrets.ADMIN_API_KEY | quote }}
  DATABASE_URL: {{ include "idenplane.databaseURL" . | quote }}
  {{- $redisURL := include "idenplane.redisURL" . }}
  {{- if $redisURL }}
  REDIS_URL: {{ $redisURL | quote }}
  {{- end }}
  {{- if .Values.secrets.REDIS_SENTINEL_HOSTS }}
  REDIS_SENTINEL_HOSTS: {{ .Values.secrets.REDIS_SENTINEL_HOSTS | quote }}
  {{- end }}
  {{- if .Values.secrets.REDIS_SENTINEL_NAME }}
  REDIS_SENTINEL_NAME: {{ .Values.secrets.REDIS_SENTINEL_NAME | quote }}
  {{- end }}
