import i18n from "i18next";
import { initReactI18next } from "react-i18next";

export const resources = {
  vi: {
    translation: {
      hr_hub: "HR Hub",
      late_hub: "Quản lý đi trễ",
      employee_workspace: "Không gian làm việc nhân sự",
      attendance_and_late_hours: "Chấm công và giờ đi trễ",
      application: "Ứng dụng",
      applications: "Ứng dụng",
      apps_not_found: "Không tìm thấy ứng dụng",
      hr_hub_portal: "Cổng thông tin nhân sự",
      portal: "Cổng thông tin",
      human_resources: "Nhân sự",
      workspace: "Không gian làm việc",
      overview: "Tổng quan",
      employees: "Nhân viên",
      attendance_and_leave: "Chấm công và nghỉ phép",
      import_history: "Lịch sử nhập dữ liệu",
      settings: "Cài đặt",
      documents: "Tài liệu",
      profile: "Hồ sơ",
      logout: "Đăng xuất",
      user: "Người dùng",
      expand_sidebar: "Mở rộng thanh bên",
      collapse_sidebar: "Thu gọn thanh bên",
      toggle_sub_items: "Bật/tắt mục con",
      employee: "Nhân viên",
      date: "Ngày",
      check_in: "Giờ vào",
      check_out: "Giờ ra",
      note: "Ghi chú",
      fine: "Tiền phạt",
      total_fine: "Tổng tiền phạt",
      grand_total: "Tổng cộng",
      actions_for_employee: "Thao tác với {{name}}",
      feedback: "Phản hồi",
      payment: "Thanh toán",
      confirm_payment: "Xác nhận thanh toán",
      reject_payment: "Hủy thanh toán",
      list_payment: "DS Thanh toán",
      detail: "Chi tiết",
      summary: "Tóm tắt",
      fine_payment: "Thanh toán tiền phạt",
      creating_payment_qr: "Đang tạo mã QR...",
      payment_qr_failed: "Không thể tạo mã QR thanh toán.",
      retry: "Thử lại",
      payment_qr: "Mã QR thanh toán",
      payment_qr_missing: "API không trả về mã QR.",
      close: "Đóng",
      copy: "Sao chép",
      copied: "Đã sao chép",
      copy_qr_url: "Sao chép đường dẫn mã QR",
      new_feedback: "Tạo phản hồi",
      attendance_details: "Thông tin chấm công",
      fine_amount: "Số tiền phạt",
      employee_feedback: "Phản hồi của nhân viên",
      reason: "Lý do",
      description: "Mô tả",
      original_fine: "Tiền phạt ban đầu",
      adjusted_amount: "Số tiền điều chỉnh",
      fine_category: "Khoản phạt",
      reduction_amount: "Mức giảm",
      no_additional_description_provided: "Không có mô tả bổ sung.",
      reduction_must_be_a_whole_amount_between_0_and_the_current_fine:
        "Mức giảm phải là số nguyên từ 0 đến số tiền phạt hiện tại.",
      reject_feedback: "Từ chối phản hồi",
      cancel: "Hủy",
      reject: "Từ chối",
      approve: "Duyệt",
      feedback_status_note: "Trạng thái phản hồi: {{status}}{{note}}",
      final_fine: "Tiền phạt sau điều chỉnh",
      leave: "Nghỉ phép",
      reason_optional: "Lý do (không bắt buộc)",
      pending: "Đang chờ",
      approved: "Đã duyệt",
      rejected: "Bị từ chối",
      wrong_time: "Sai thời gian chấm công",
      wrong_fine: "Sai tiền phạt",
      early_leave_permission: "Có phép về sớm",
      late_permission: "Có phép đi muộn",
      other: "Khác",
      status_feedback_reason_reduction:
        "{{status}} phản hồi: {{reason}} {{reduction}}",
      all_feedback: "Tất cả phản hồi",
      loading_feedback: "Đang tải phản hồi",
      loading_details: "Đang tải chi tiết",
      feedback_details_are_unavailable:
        "Không có thông tin chi tiết về phản hồi này.",
      feedback_month: "Phản hồi · {{month}}",
      feedback_list: "← Danh sách phản hồi",
      unable_to_review_feedback_please_try_again:
        "Không thể duyệt phản hồi. Vui lòng thử lại.",
      no_feedback_for_month: "Không có phản hồi trong {{month}}.",
      no_filter_feedback: "Không có phản hồi với trạng thái {{filter}}.",
      select_a_feedback_item_to_review: "Chọn một phản hồi để xem xét.",
      fullscreen: "Toàn màn hình",
      only_excel_files_xlsx_xls_are_supported:
        "Chỉ hỗ trợ tệp Excel (.xlsx, .xls).",
      please_select_at_least_2_excel_files:
        "Vui lòng chọn ít nhất 2 tệp Excel.",
      invalid_files: "Tệp không hợp lệ.",
      attendance_file_must_contain_bcc_in_its_filename:
        'Tên tệp chấm công phải chứa "BCC".',
      only_one_attendance_file_containing_bcc_is_allowed:
        'Chỉ được chọn một tệp chấm công có tên chứa "BCC".',
      please_select_exactly_2_files_one_bcc_attendance_file_and_one_leave_file:
        "Vui lòng chọn đúng 2 tệp: một tệp chấm công BCC và một tệp nghỉ phép.",
      failed_to_import_workforce_data: "Không thể nhập dữ liệu nhân sự.",
      import_hr_data: "Nhập dữ liệu nhân sự",
      select_at_least_two_excel_files_the_file_containing:
        "Chọn ít nhất hai tệp Excel. Tệp có tên chứa",
      will_be_treated_as_attendance_details_the_other_file_will_be_treated_as_leave_details:
        "sẽ được dùng làm dữ liệu chấm công. Tệp còn lại sẽ được dùng làm dữ liệu nghỉ phép.",
      choose_files: "Chọn tệp",
      choose_excel_files: "Chọn tệp Excel",
      select_attendance_and_leave_files: "Chọn tệp chấm công và nghỉ phép",
      browse_files: "Duyệt tệp",
      selected_files: "Tệp đã chọn",
      import_mapping: "Phân loại dữ liệu nhập",
      remove_file: "Xóa tệp",
      import_data: "Nhập dữ liệu",
      review_imported_attendance: "Xem xét dữ liệu chấm công đã nhập",
      attendance_view: "Dữ liệu chấm công",
      review_attendance_violations_and_calculated_fines_before_continuing:
        "Kiểm tra vi phạm chấm công và tiền phạt đã tính trước khi tiếp tục.",
      exit_full_screen: "Thoát toàn màn hình",
      full_screen: "Toàn màn hình",
      confirm_import: "Xác nhận nhập dữ liệu",
      attendance_and_leave_import_history:
        "Chấm công và nghỉ phép > Lịch sử nhập dữ liệu",
      previous_attendance_and_leave_imports:
        "Các lần nhập dữ liệu chấm công và nghỉ phép trước đây",
      imported: "Thời gian nhập",
      month: "Tháng",
      status: "Trạng thái",
      attendance: "Chấm công",
      confirmed: "Đã xác nhận",
      preview: "Bản xem trước",
      view: "Xem",
      loading_import_history: "Đang tải lịch sử nhập dữ liệu...",
      failed_to_load_import_history: "Không thể tải lịch sử nhập dữ liệu.",
      no_import_history_yet: "Chưa có lịch sử nhập dữ liệu.",
      select_month: "Chọn tháng",
      review_employee_attendance_late_hours_and_leave_records:
        "Xem dữ liệu chấm công, giờ đi trễ và nghỉ phép của nhân viên.",
      attendance_overview: "Tổng quan chấm công",
      monthly_attendance_and_leave_summary:
        "Tổng hợp chấm công và nghỉ phép theo tháng",
      percent_reviewed: "{{percent}}% đã xem xét",
      percent_approved: "{{percent}}% đã duyệt",
      attendance_and_leave_data: "Dữ liệu chấm công và nghỉ phép",
      data_imported: "Đã nhập",
      not_yet_imported: "Chưa nhập",
      review_employee_attendance: "Xem xét chấm công nhân viên",
      open_the_detailed_late_hub_review_for_this_month:
        "Mở phần xem xét chi tiết đi trễ trong tháng này.",
      view_details: "Xem chi tiết",
      employees_in_this_report: "Số nhân viên trong báo cáo",
      attendance_records: "Lượt chấm công",
      imported_attendance_records: "Lượt chấm công đã nhập",
      late_employees: "Nhân viên đi trễ",
      employees_with_late_records: "Nhân viên có ghi nhận đi trễ",
      total_fines: "Tổng tiền phạt",
      total_attendance_fines: "Tổng tiền phạt chấm công",
      approved_feedback: "Phản hồi đã duyệt",
      attendance_report: "Báo cáo chấm công",
      no_attendance_data: "Không có dữ liệu chấm công",
      unpaid: "Chưa thanh toán",
      paid: "Đã thanh toán",
      reviewing: "Đang xem xét",
      department: "Phòng ban",
      late: "Đi trễ",
      minutes: "phút",
      appeal: "Khiếu nại",
      payment_history: "Lịch sử thanh toán",
      search_employees: "Tìm nhân viên...",
      all: "Tất cả",
      count_employees: "{{count}} nhân viên",
      loading: "Đang tải...",
      no_employees_found: "Không tìm thấy nhân viên.",
      employee_name: "Nhân viên",
      late_minutes: "Số phút đi trễ",
      sort_by_column: "Sắp xếp theo {{column}}",
      rules: "Quy tắc",
      workforce_rules: "Quy tắc nhân sự",
      configure_attendance_exceptions_and_overrides:
        "Cấu hình ngoại lệ và thiết lập ghi đè cho chấm công.",
      add_rule: "Thêm quy tắc",
      loading_rules: "Đang tải quy tắc...",
      rule: "Quy tắc",
      value: "Giá trị",
      all_employees: "Tất cả nhân viên",
      weekday: "Ngày trong tuần",
      every_day: "Hằng ngày",
      start: "Bắt đầu",
      end: "Kết thúc",
      priority: "Mức ưu tiên",
      enabled: "Đang bật",
      disabled: "Đã tắt",
      deleting: "Đang xóa...",
      delete: "Xóa",
      clone_workforce_rule: "Sao chép quy tắc nhân sự",
      edit_workforce_rule: "Chỉnh sửa quy tắc nhân sự",
      add_workforce_rule: "Thêm quy tắc nhân sự",
      select_rule: "Chọn quy tắc",
      leave_empty_for_all_employees: "Để trống để áp dụng cho tất cả nhân viên",
      optional_reason: "Lý do không bắt buộc",
      enabled_label: "Bật quy tắc",
      attendance_and_leave_settings_breadcrumb:
        "Chấm công và nghỉ phép > Cài đặt",
      attendance_and_leave_settings: "Cài đặt chấm công và nghỉ phép",
      morning_start: "Giờ bắt đầu buổi sáng",
      morning_end: "Giờ kết thúc buổi sáng",
      morning_checkout_deadline: "Hạn chấm công buổi sáng",
      afternoon_start: "Giờ bắt đầu buổi chiều",
      afternoon_checkout_deadline: "Hạn chấm công buổi chiều",
      fine_late_morning: "Phạt đi muộn buổi sáng",
      fine_late_afternoon: "Phạt đi muộn buổi chiều",
      fine_no_checkout_half_day: "Phạt thiếu chấm công ra về (nửa ngày)",
      fine_no_checkout_full_day: "Phạt thiếu chấm công ra về (cả ngày)",
      delete_this_rule: "Xóa quy tắc này?",
      this_action_cannot_be_undone: "Bạn không thể hoàn tác thao tác này.",
      clone_rule: "Sao chép quy tắc",
      edit_rule: "Chỉnh sửa quy tắc",
      delete_rule: "Xóa quy tắc",
      start_date: "Ngày bắt đầu",
      end_date: "Ngày kết thúc",
      saving: "Đang lưu...",
      save_changes: "Lưu thay đổi",
      monday: "Thứ Hai",
      tuesday: "Thứ Ba",
      wednesday: "Thứ Tư",
      thursday: "Thứ Năm",
      friday: "Thứ Sáu",
      saturday: "Thứ Bảy",
      sunday: "Chủ Nhật",
      authentication_failed_message: "Xác thực không thành công.",
      authentication_failed: "Xác thực không thành công",
      signing_you_in: "Đang đăng nhập...",
      feedback_submit_failed: "Không thể gửi phản hồi. Vui lòng thử lại.",
      send_feedback: "Gửi phản hồi",
      app_1: "Ứng dụng 1",
      app_2: "Ứng dụng 2",
      engineering: "Kỹ thuật",
      product: "Sản phẩm",
      hr: "Nhân sự",
      actions: "Thao tác",
      rule_value_example: "Ví dụ: 08:30 / 30000 / true",
      sending: "Đang gửi...",
      select_employee: "Chọn nhân viên",
      employees_selected: "nhân viên đã chọn",
      search_employee: "Tìm kiếm nhân viên...",
      no_employee_found: "Không tìm thấy nhân viên",
      clear: "Xóa",
      click_on_employee_to_view_attendance_detail:
        "Nhấn để xem chi tiết chấm công",
      employee_has_pending_payment:
        "Nhân viên này đã có giao dịch thanh toán đang chờ xử lý.",
      view_transaction: "Xem giao dịch",
      monthly_fines: "Các khoản phạt theo tháng",
      select_months_to_pay: "Chọn các tháng cần thanh toán",
      deselect_all: "Bỏ chọn tất cả",
      select_all: "Chọn tất cả",
      reduction: "Giảm trừ",
      payable_amount: "Số tiền phải thanh toán",
      no_available_fines: "Không có khoản phạt nào có thể thanh toán.",
      total: "Tổng cộng",
      selected_months: "Số tháng đã chọn",
      payment_preview_failed: "Không thể tải thông tin thanh toán.",
      payment_failed: "Không thể tạo giao dịch thanh toán.",
      create_payment: "Tạo thanh toán",
      payment_transaction: "Giao dịch thanh toán",
      payment_id: "Mã giao dịch",
      amount: "Số tiền",
      payment_method: "Phương thức thanh toán",
      provider: "Nhà cung cấp",
      provider_payment_id: "Mã giao dịch nhà cung cấp",
      open_payment: "Mở thanh toán",
      back: "Quay lại",
      confirm_fine_payment: "Xác nhận thanh toán tiền phạt",
      payment_transactions_failed: "Không thể tải các giao dịch thanh toán.",
      no_pending_transactions:
        "Không có giao dịch thanh toán nào đang chờ xử lý.",
      all_payments_settled: "Tất cả giao dịch đã được thanh toán.",
      pending_transactions: "Giao dịch đang chờ xử lý",
      transactions: "giao dịch",
      settling_payment: "Đang xác nhận thanh toán...",
      selected_transactions: "Giao dịch đã chọn",
      payment_settle_failed: "Không thể xác nhận thanh toán.",
      created_at: "Thời gian tạo",
      expires_at: "Thời gian hết hạn",
    },
  },
} as const;

i18n.use(initReactI18next).init({
  resources,
  lng: "vi",
  fallbackLng: "vi",
  supportedLngs: ["vi"],
  interpolation: { escapeValue: false },
});

export default i18n;
